*** empty log message ***

diff --git a/gg/sfdc/trunk/configure b/gg/sfdc/trunk/configure
--- a/gg/sfdc/trunk/configure
+++ b/gg/sfdc/trunk/configure
@@ -916,12 +916,15 @@ fi
 PATH_SEPARATOR="$ac_path_separator"
 rm -f conftest.sh
 
+VERSION=1.0
+DATE=2003-07-23
+
 # Checks for programs.
 for ac_prog in perl
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:924: checking for $ac_word" >&5
+echo "$as_me:927: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_PERL+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -936,7 +939,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_PERL="$ac_prog"
-echo "$as_me:939: found $ac_dir/$ac_word" >&5
+echo "$as_me:942: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -944,16 +947,16 @@ fi
 fi
 PERL=$ac_cv_prog_PERL
 if test -n "$PERL"; then
-  echo "$as_me:947: result: $PERL" >&5
+  echo "$as_me:950: result: $PERL" >&5
 echo "${ECHO_T}$PERL" >&6
 else
-  echo "$as_me:950: result: no" >&5
+  echo "$as_me:953: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
   test -n "$PERL" && break
 done
-test -n "$PERL" || PERL="{ { echo "$as_me:956: error: \"Perl is required\"" >&5
+test -n "$PERL" || PERL="{ { echo "$as_me:959: error: \"Perl is required\"" >&5
 echo "$as_me: error: \"Perl is required\"" >&2;}
    { (exit 1); exit 1; }; } "
 
@@ -961,7 +964,7 @@ for ac_prog in pod2text
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:964: checking for $ac_word" >&5
+echo "$as_me:967: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_POD2TEXT+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -976,7 +979,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_POD2TEXT="$ac_prog"
-echo "$as_me:979: found $ac_dir/$ac_word" >&5
+echo "$as_me:982: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -984,16 +987,16 @@ fi
 fi
 POD2TEXT=$ac_cv_prog_POD2TEXT
 if test -n "$POD2TEXT"; then
-  echo "$as_me:987: result: $POD2TEXT" >&5
+  echo "$as_me:990: result: $POD2TEXT" >&5
 echo "${ECHO_T}$POD2TEXT" >&6
 else
-  echo "$as_me:990: result: no" >&5
+  echo "$as_me:993: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
   test -n "$POD2TEXT" && break
 done
-test -n "$POD2TEXT" || POD2TEXT="{ { echo "$as_me:996: error: \"pod2text is required\"" >&5
+test -n "$POD2TEXT" || POD2TEXT="{ { echo "$as_me:999: error: \"pod2text is required\"" >&5
 echo "$as_me: error: \"pod2text is required\"" >&2;}
    { (exit 1); exit 1; }; } "
 
@@ -1001,7 +1004,7 @@ for ac_prog in pod2man
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:1004: checking for $ac_word" >&5
+echo "$as_me:1007: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_POD2MAN+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1016,7 +1019,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_POD2MAN="$ac_prog"
-echo "$as_me:1019: found $ac_dir/$ac_word" >&5
+echo "$as_me:1022: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -1024,16 +1027,16 @@ fi
 fi
 POD2MAN=$ac_cv_prog_POD2MAN
 if test -n "$POD2MAN"; then
-  echo "$as_me:1027: result: $POD2MAN" >&5
+  echo "$as_me:1030: result: $POD2MAN" >&5
 echo "${ECHO_T}$POD2MAN" >&6
 else
-  echo "$as_me:1030: result: no" >&5
+  echo "$as_me:1033: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
   test -n "$POD2MAN" && break
 done
-test -n "$POD2MAN" || POD2MAN="{ { echo "$as_me:1036: error: \"pod2man is required\"" >&5
+test -n "$POD2MAN" || POD2MAN="{ { echo "$as_me:1039: error: \"pod2man is required\"" >&5
 echo "$as_me: error: \"pod2man is required\"" >&2;}
    { (exit 1); exit 1; }; } "
 
@@ -1054,7 +1057,7 @@ for ac_dir in $srcdir $srcdir/.. $srcdir/../..; do
   fi
 done
 if test -z "$ac_aux_dir"; then
-  { { echo "$as_me:1057: error: cannot find install-sh or install.sh in $srcdir $srcdir/.. $srcdir/../.." >&5
+  { { echo "$as_me:1060: error: cannot find install-sh or install.sh in $srcdir $srcdir/.. $srcdir/../.." >&5
 echo "$as_me: error: cannot find install-sh or install.sh in $srcdir $srcdir/.. $srcdir/../.." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -1074,7 +1077,7 @@ ac_configure="$SHELL $ac_aux_dir/configure" # This should be Cygnus configure.
 # AFS /usr/afsws/bin/install, which mishandles nonexistent args
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
-echo "$as_me:1077: checking for a BSD compatible install" >&5
+echo "$as_me:1080: checking for a BSD compatible install" >&5
 echo $ECHO_N "checking for a BSD compatible install... $ECHO_C" >&6
 if test -z "$INSTALL"; then
 if test "${ac_cv_path_install+set}" = set; then
@@ -1123,7 +1126,7 @@ fi
     INSTALL=$ac_install_sh
   fi
 fi
-echo "$as_me:1126: result: $INSTALL" >&5
+echo "$as_me:1129: result: $INSTALL" >&5
 echo "${ECHO_T}$INSTALL" >&6
 
 # Use test -z because SunOS4 sh mishandles braces in ${var-val}.
@@ -1142,7 +1145,7 @@ test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
 # Checks for library functions.
 
-ac_config_files="$ac_config_files Makefile"
+ac_config_files="$ac_config_files Makefile gg-sfdc.spec"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -1253,7 +1256,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1256: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1259: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1421,7 +1424,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1424: error: ambiguous option: $1
+    { { echo "$as_me:1427: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1440,7 +1443,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1443: error: unrecognized option: $1
+  -*) { { echo "$as_me:1446: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1476,7 +1479,8 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
-  *) { { echo "$as_me:1479: error: invalid argument: $ac_config_target" >&5
+  "gg-sfdc.spec" ) CONFIG_FILES="$CONFIG_FILES gg-sfdc.spec" ;;
+  *) { { echo "$as_me:1483: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1560,6 +1564,8 @@ s,@ECHO_T@,$ECHO_T,;t t
 s,@PATH_SEPARATOR@,$PATH_SEPARATOR,;t t
 s,@DEFS@,$DEFS,;t t
 s,@LIBS@,$LIBS,;t t
+s,@VERSION@,$VERSION,;t t
+s,@DATE@,$DATE,;t t
 s,@PERL@,$PERL,;t t
 s,@POD2TEXT@,$POD2TEXT,;t t
 s,@POD2MAN@,$POD2MAN,;t t
@@ -1680,7 +1686,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1683: creating $ac_file" >&5
+    { echo "$as_me:1689: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1698,7 +1704,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1701: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1707: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1711,7 +1717,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1714: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1720: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
