Load libnix-2.0/ into gg/libnix/trunk.

diff --git a/gg/libnix/trunk/configure b/gg/libnix/trunk/configure
--- a/gg/libnix/trunk/configure
+++ b/gg/libnix/trunk/configure
@@ -2525,6 +2525,53 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL}'
 
 test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
+for ac_prog in SFDC sfdc
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:2532: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_SFDC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$SFDC"; then
+  ac_cv_prog_SFDC="$SFDC" # Let the user override the test.
+else
+  ac_save_IFS=$IFS; IFS=$ac_path_separator
+ac_dummy="$PATH"
+for ac_dir in $ac_dummy; do
+  IFS=$ac_save_IFS
+  test -z "$ac_dir" && ac_dir=.
+  $as_executable_p "$ac_dir/$ac_word" || continue
+ac_cv_prog_SFDC="$ac_prog"
+echo "$as_me:2547: found $ac_dir/$ac_word" >&5
+break
+done
+
+fi
+fi
+SFDC=$ac_cv_prog_SFDC
+if test -n "$SFDC"; then
+  echo "$as_me:2555: result: $SFDC" >&5
+echo "${ECHO_T}$SFDC" >&6
+else
+  echo "$as_me:2558: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$SFDC" && break
+done
+
+CPPFLAGS="${CPPFLAGS} -I`pwd`/sources/headers"
+
+ac_config_commands="$ac_config_commands sources/headers/inline"
+
+ac_config_commands="$ac_config_commands sources/headers/inline/amitcp.h"
+
+ac_config_commands="$ac_config_commands sources/headers/inline/as225.h"
+
+ac_config_commands="$ac_config_commands sources/headers/inline/usergroup.h"
+
 ac_config_files="$ac_config_files Makefile sources/Makefile sources/amiga/Makefile sources/math/Makefile sources/misc/Makefile sources/nix/Makefile sources/nix13/Makefile sources/nixmain/Makefile sources/nix_main/Makefile sources/socket/Makefile sources/stack/Makefile sources/startup/Makefile sources/stubs/Makefile examples/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -2635,7 +2682,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:2638: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:2685: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -2753,6 +2800,9 @@ Usage: $0 [OPTIONS] [FILE]...
 Configuration files:
 $config_files
 
+Configuration commands:
+$config_commands
+
 Report bugs to <bug-autoconf@gnu.org>."
 EOF
 
@@ -2803,7 +2853,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:2806: error: ambiguous option: $1
+    { { echo "$as_me:2856: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -2822,7 +2872,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:2825: error: unrecognized option: $1
+  -*) { { echo "$as_me:2875: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -2852,6 +2902,17 @@ on `(hostname || uname -n) 2>/dev/null | sed 1q`
 _ACEOF
 EOF
 
+cat >>$CONFIG_STATUS <<EOF
+#
+# INIT-COMMANDS section.
+#
+
+SFDC=${SFDC} host=${host}
+SFDC=${SFDC} host=${host}
+SFDC=${SFDC} host=${host}
+
+EOF
+
 cat >>$CONFIG_STATUS <<\EOF
 for ac_config_target in $ac_config_targets
 do
@@ -2871,7 +2932,11 @@ do
   "sources/startup/Makefile" ) CONFIG_FILES="$CONFIG_FILES sources/startup/Makefile" ;;
   "sources/stubs/Makefile" ) CONFIG_FILES="$CONFIG_FILES sources/stubs/Makefile" ;;
   "examples/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/Makefile" ;;
-  *) { { echo "$as_me:2874: error: invalid argument: $ac_config_target" >&5
+  "sources/headers/inline" ) CONFIG_COMMANDS="$CONFIG_COMMANDS sources/headers/inline" ;;
+  "sources/headers/inline/amitcp.h" ) CONFIG_COMMANDS="$CONFIG_COMMANDS sources/headers/inline/amitcp.h" ;;
+  "sources/headers/inline/as225.h" ) CONFIG_COMMANDS="$CONFIG_COMMANDS sources/headers/inline/as225.h" ;;
+  "sources/headers/inline/usergroup.h" ) CONFIG_COMMANDS="$CONFIG_COMMANDS sources/headers/inline/usergroup.h" ;;
+  *) { { echo "$as_me:2939: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -2883,6 +2948,7 @@ done
 # bizarre bug on SunOS 4.1.3.
 if $ac_need_defaults; then
   test "${CONFIG_FILES+set}" = set || CONFIG_FILES=$config_files
+  test "${CONFIG_COMMANDS+set}" = set || CONFIG_COMMANDS=$config_commands
 fi
 
 # Create a temporary directory, and hook for its removal unless debugging.
@@ -2981,6 +3047,7 @@ s,@AWK@,$AWK,;t t
 s,@INSTALL_PROGRAM@,$INSTALL_PROGRAM,;t t
 s,@INSTALL_SCRIPT@,$INSTALL_SCRIPT,;t t
 s,@INSTALL_DATA@,$INSTALL_DATA,;t t
+s,@SFDC@,$SFDC,;t t
 CEOF
 
 EOF
@@ -3095,7 +3162,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:3098: creating $ac_file" >&5
+    { echo "$as_me:3165: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -3113,7 +3180,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3116: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3183: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3126,7 +3193,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3129: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3196: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -3153,6 +3220,29 @@ s,@INSTALL@,$ac_INSTALL,;t t
     rm -f $tmp/out
   fi
 
+done
+EOF
+cat >>$CONFIG_STATUS <<\EOF
+
+#
+# CONFIG_COMMANDS section.
+#
+for ac_file in : $CONFIG_COMMANDS; do test "x$ac_file" = x: && continue
+  ac_dest=`echo "$ac_file" | sed 's,:.*,,'`
+  ac_source=`echo "$ac_file" | sed 's,[^:]*:,,'`
+
+  case $ac_dest in
+    sources/headers/inline ) mkdir -p sources/headers/inline ;;
+    sources/headers/inline/amitcp.h ) ${SFDC} --target=$host --mode=macros \
+		    ${srcdir}/sources/headers/sfd/amitcp.sfd \
+		    -o sources/headers/inline/amitcp.h ;;
+    sources/headers/inline/as225.h ) ${SFDC} --target=$host --mode=macros \
+		    ${srcdir}/sources/headers/sfd/as225.sfd \
+		    -o sources/headers/inline/as225.h ;;
+    sources/headers/inline/usergroup.h ) ${SFDC} --target=$host --mode=macros \
+		    ${srcdir}/sources/headers/sfd/usergroup.sfd \
+		    -o sources/headers/inline/usergroup.h ;;
+  esac
 done
 EOF
 
